### ISSUE TITLE
Fix links to contest materials

### ISSUE THREAD

**Issue by austrin** [icpc/ncpc-web#7]
The links to contest materials for several years are broken because they were large and do not fit within Githubs 100 Mb file size limit.

Apparently there is some way to add large static files like these to a web page by attaching them to a release instead of keeping them in the repository.  That sounds like a good fix to me and is nice because it also makes cloning the repository faster.

When doing this the links to 2019's contest materials should also be fixed (currently they point to files hosted on my Google Drive).

**Comment by exoji2e** [comment]
I have fixed this just now by putting all previous ncpc data as releases to this repo, and made a git filter-repo to rewrite the history to remove the big files (which made deployment take like 10 minutes previously).
